language: php
php:
  - "5.4"
  - "5.3"
env:
  - DB=mysql
before_script:
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - echo "extension=imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pear config-set preferred_state stable
  - pear install pear/PHP_CodeSniffer
  - pear config-set auto_discover 1
  - pear install pear.phpunit.de/phpcpd
  - pear install pear.phpunit.de/PHP_CodeCoverage
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash
script:
  - phpunit -c application/tests/phpunit.xml
  - phpcs --standard=PSR2 --extensions=php --ignore=*/libraries/*,*/archive/* .
  - phpmd . text codesize,unusedcode,naming,design --ignore=application/libraries/,application/archive/